### ISSUE TITLE
LIVE containers with external data files

### ISSUE THREAD

**Issue by gibbed** [xenia-project/xenia#1272]
The Twitch app available on the 360 Apps section's base container file is split into two files:

`334A07D1\00007000\57E8FFEC1B9DEE15ECCE39F602FBD6E333`
`334A07D1\00007000\57E8FFEC1B9DEE15ECCE39F602FBD6E333.data\Data0000`

`BlockToOffsetSTFS(0)` returns `0xD000` which is larger than the main container file.

Xenia currently cannot handle containers split into multiple files like this.

There is likely a flag in the header to indicate data is present in external files instead of the main container file.

I simply appended `Data0000` to the end of the main container file and then `xenia-vfs-dump` was able to unpack it correctly.

**Comment by gibbed** [comment]
Apparently #1254 addresses this, but I'll leave this open until it's resolved in master.

**Comment by Wildenhaus** [comment]
I still have a bit more testing to do, but from what I understand it works as follows:
- The 44kb file in the root path is the header. All SVOD packages have this regardless of the number of files they are comprised of. It is 0xB000 bytes long and contains a LIVE, PIRS, or CON magic.
- Following the header is the first set of L0 and L1 hash blocks, each of length 0x1000. L0 contains 0xCC hashes and occurs every 0x198 blocks. L1 occurs every 0xCB L0 blocks (or 0xA1C4 L0 hashes). Hashes represent two blocks each.
- Each data file is limited to a size of 0xA290000 (0xA1C4 * 2 * 0x800 = 0xA1C4000 + hash blocks).
- There is no explicit flag to denote fragmented packages. Rather, the kernel seems to check for fragments based on the block count in the SVOD header and then maps the .data folder. Currently #1254 just checks for the presence of a .data folder and maps those instead.

The current problem with my PR is that it isn't correctly taking the block offset value of the SVOD header into account. For containers made using Iso2God, this isn't a problem, as the offset is always zero, but for digital download games from the marketplace, they seem to have an arbitrary offset that usually underflows the current code, and I haven't yet worked out the math behind it.

**Comment by Margen67** [comment]
#1254 was merged over 2 years ago...
