### ISSUE TITLE
[APU] Sounds don't loop seamlessly

### ISSUE THREAD

**Issue by JoelLinn** [xenia-project/xenia#1515]
Looped sounds have a short interruption.
Confirmed for rain in Red Dead Redemption and engine sounds in [Midnight Club: Los Angeles](https://www.youtube.com/watch?v=-uYtTg30AwM).

These should play seamlessly.
My vague guess is that the XMA codec implementation doesn't handle this correctly.

**Comment by illusion98** [comment]
Same issue for Engine sounds in [Grand Theft Auto IV](https://youtu.be/VscxdZs3Y5o)

**Comment by Thomas-Geraghty** [comment]
Same issue with looping sounds exists on Geometry Wars 2

**Comment by Raijin56** [comment]
Is there some solution to this? I'd love to play RDR in Xenia but at least for me this bug makes it unplayable being sound so fundamental ☹️

**Comment by Sterophonick** [comment]
In games such as Alien Hominid HD and Pinball FX, audio looping doesn't even work at all. :/

**Comment by JoelLinn** [comment]
> Is there some solution to this? I'd love to play RDR in Xenia but at least for me this bug makes it unplayable being sound so fundamental

How does it make it unplayable? I played through it and apart from rain and car sounds there where zero issues with sounds.

**Comment by Raijin56** [comment]
> > Is there some solution to this? I'd love to play RDR in Xenia but at least for me this bug makes it unplayable being sound so fundamental
> 
> How does it make it unplayable? I played through it and apart from rain and car sounds there where zero issues with sounds.

Try to play the game with an emulator of the PS3 version. You'll notice the difference quickly in the starting screen. Or see a video in YouTube of the Xbox version instead. You'll notice how full of ambient sounds the game is, and Xenia unfortunately don't play them correctly, it seems like they start and immediately shut off because they don't loop correctly.

**Comment by JoelLinn** [comment]
> > > Is there some solution to this? I'd love to play RDR in Xenia but at least for me this bug makes it unplayable being sound so fundamental
> > 
> > 
> > How does it make it unplayable? I played through it and apart from rain and car sounds there where zero issues with sounds.
> 
> Try to play the game with an emulator of the PS3 version. You'll notice the difference quickly in the starting screen. Or see a video in YouTube of the Xbox version instead. You'll notice how full of ambient sounds the game is, and Xenia unfortunately don't play them correctly, it seems like they start and immediately shut off because they don't loop correctly.

I'm sorry I can't really make out a significant difference. https://www.youtube.com/watch?v=T5G-xELA6EA&
When did you last check? There was an issue with the clock that had the sounds immediately stop if played at all, just how you described. But that I fixed ages ago.

**Comment by fuhuan416** [comment]
Tekken 6 BGM same, but sound effect heards normal.

**Comment by Raijin56** [comment]
I would like to share some samples of the problem with the audio loops in ambient sound.

Wind: https://youtu.be/fF-aBjFtksI
Water: https://youtu.be/3iQJaK3Kh9Y
Rain: https://youtu.be/O-sU6NP-DWE
Cricket: https://youtu.be/8235rNSJ48k

Hope it's useful. Kind regards!

**Comment by ForbiddenDonut99** [comment]
Many of the looping ambient sound effects in Condemned 2: Bloodshot abruptly end after one loop. Likely the same cause as the issues in this ticket.

**Comment by Gliniak** [comment]
Seems like this issue should be resolved since #1808.  Can someone additionally confirm it before I close it?

**Comment by SanfordJMorgan** [comment]
No, the problem still remains in Condemned: Criminal Origins.
